name: GdUnit4 Tests
on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Build `resource_test_rust`
        run: cargo build -p resource_test_rust --verbose
      
      - name: print working project_dir
        run: pwd

      - name: ls
        run: ls

      - uses: MikeSchulze/gdunit4-action@v1
        with:
          project_dir: './resource_test_godot_project/'
          godot-version: '4.4.1'
          paths: 'res://unit_test.gd'